### ISSUE TITLE
How do I specify columns orders when loading form an array of JSON objects?

### ISSUE THREAD

**Issue by tddschn** [thombashi/sqlitebiter#103]
# Is your feature request related to a problem? Please describe.

I'm loading from a JSON file with an array of objects with keys `b, a` and the generated sqlite database will have column a before b. I know the key value pairs in a JSON object is unordered, so I am wondering if I can specify the order of columns in the output database.

# Describe the solution you'd like

Maybe add a command line arg like this: `--column-order b,a`.

# Describe alternatives you've considered

# Additional context

**Comment by thombashi** [comment]
@tddschn 
I couldn't quite figure out the situation where the columns needed to be reordered.
You can specify a query like `SELECT b, a FROM xxx`. Does this not work for you?"
If so, could you describe your situation in more detail?
