### ISSUE TITLE
Conversion fails without errors on JSON

### ISSUE THREAD

**Issue by tmikaeld** [thombashi/sqlitebiter#11]
Even when using the exact sample provided in the docs.

````json
{
    "type": "object",
    "additionalProperties": {
        "type": "array",
        "items": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    {"type": "string"},
                    {"type": "number"},
                    {"type": "null"}
                ]
            }
        }
    }
}
````

**Comment by thombashi** [comment]
@tmikaeld 
Thank you for pointing it out.

Actually, that is not a sample of JSON data but a `JSON schema` which describes acceptable JSON format. It is confusing though. I think that problems are:

1) there is no concrete example of valid JSON data in the document
A sample of JSON data coincides with JSON schema that you mentioned is as follows:

```json
{
    "table_a" : [
        {"attr_b": 4, "attr_c": "a", "attr_a": 1},
        {"attr_b": 2.1, "attr_c": "bb", "attr_a": 2},
        {"attr_b": 120.9, "attr_c": "ccc", "attr_a": 3}
    ],
    "table_b" : [
        {"a": 1, "b": 4},
        {"a": 2 },
        {"a": 3, "b": 120.9}
    ]
}
```

I will add example data to the document.

2) no error message displayed when you set invalid JSON files in the command option
I would add an error message if the conversion failed.


I think these modifications will reduce confusion of users.
How do you feel about this?

**Comment by tmikaeld** [comment]
Ah, ok, i misunderstood the purpose of the tool.
What i was after was a way to convert a JSON Schema into SQL/SQLite.

But such a tool doesn't seem to exist, even though it should be very well possible (and a huge time-saver).

**Comment by tmikaeld** [comment]
And i agree about making it clearer when parsing a Schema instead of JSON data, should be fairly easy to check 👍

**Comment by thombashi** [comment]
Thank you for your response 👍 

>Ah, ok, i misunderstood the purpose of the tool.
What i was after was a way to convert a JSON Schema into SQL/SQLite (Schema).
But such a tool doesn't seem to exist, even though it should be very well possible (and a huge time-saver).

That is right. Unfortunately, this tool has no capability of to do that.

**Comment by thombashi** [comment]
I've updated the package to `0.1.6`.
It's not what you want though.
Anyway thank you for the issue.
I will close this issue.

**Comment by tmikaeld** [comment]
That's no problem @thombashi, I'm glad you answered the issue 👍  
Have a great day!
