### ISSUE TITLE
csv conversion to sqlite creates an empty file

### ISSUE THREAD

**Issue by priyankasebastian** [thombashi/sqlitebiter#23]
index,No,Player_last_name,Age,Team
1, 55, D Sam, 31, Raven
2, 36, J Ifdgg, 30, Raven
3, 91, K Wedfb, 28, Raven

**Comment by priyankasebastian** [comment]
http://pytablereader.readthedocs.io/en/latest/pages/reference/loader.html#json-loader-classes 

the link above is not letting in even after signingup

**Comment by thombashi** [comment]
@priyankasebastian 
Thank you for your repot.

I believe I've fix the problem with `sqlitebiter 0.4.1-alpha`.
Would you upgrade sqlitebiter and re-execute the command?
You could upgrade with `pip install sqlitebiter --upgrade --pre`

**Comment by thombashi** [comment]
>the link above is not letting in even after signingup

And I've also fix the missing link.
The link intended to navigate to http://pytablereader.readthedocs.io/en/latest/pages/reference/format_specific_loader.html#json-loader-classes

**Comment by priyankasebastian** [comment]
Thank you. @thombashi 
 csv file conversions are working now. Also the link to documentation.
