### ISSUE TITLE
Append data

### ISSUE THREAD

**Issue by johnzastrow** [thombashi/sqlitebiter#35]
**Feature request: Love this project even as I try to debug some JSON loading. But I think it's going to be AMAZINGLY helpful. Any chance of getting an append option for data that match an existing table structure?**

**Comment by thombashi** [comment]
@johnzastrow

>Any chance of getting an append option for data that match an existing table structure?

Thank you for your request.
I'll consider the feature for the future release.

>I try to debug some JSON loading.

As you may already be aware, loadable JSON schema for sqlitebiter are limited (described in http://pytablereader.rtfd.io/en/latest/pages/reference/format_specific_loader.html#json-loader-classes).
If you could provide me with a troubled JSON file information, I could help you with your problem.

**Comment by thombashi** [comment]
@johnzastrow
I've updated `sqlitebiter` to `0.9.0`.
From this version, you can use `--append` option properly.
