### ISSUE TITLE
access google sheets without authentication

### ISSUE THREAD

**Issue by aculich** [thombashi/sqlitebiter#45]
@rcf18 and I would like to be able to access google sheets without authentication for those sheets where "Anyone with the link can view the spreadsheet" has been set as an option.

```
sqlitebiter -v gs https://docs.google.com/spreadsheets/d/1Wd0RMKAMaTptZ43Bcll664HL9HtMjExrL4
AmDHCee-A/edit

Usage: sqlitebiter gs [OPTIONS] CREDENTIALS TITLE
```

Anyone working on enabling that as a feature yet?

Thanks!

**Comment by thombashi** [comment]
As far as I know, google sheets API does not have the interface to access to sheets without authentication (even if public sheets). However. I could be enhanced to convert only the first sheet in the book by scraping from a public google sheets URL.
Is this enough for your use case?
If yes, I would try to implement the feature.

Thanks,

**Comment by rcf18** [comment]
hi there, thanks for responding right away!  
yes, if you'll be interested in doing that, we can then continue with the practice session that we started the other day. thanks in advance!

**Comment by thombashi** [comment]
Thank for your answer.

I found another limitations to convert from a public google sheets URL as it is
(number of columns limited to 26, and number of rows limited to 100).
So, it may not an effective solution.

I found two workarounds.
Both of the methods can convert the whole book (even when included multiple sheets).
Are these workarounds could solve your issue?

- a. Publish the book as a web page and convert the page by using `sqlitebiter url` subcommand
- b. Download as an Excel file and convert the file by using `sqlitebiter file` subcommand

# a. Publish the book
1. Select menu: `File` -> `Publish to the web`
2. Select `Link` tab
3. Select `Entire Document` and `Web page`
4. Press `Publish` button
    - If you check `Automatically republish when changes are made` the page automatically update when you edit the page
5. Convert from the published web page URL to a SQLite file by using `sqlitebiter url` subcommand
    - In this method, sheet names are dropped during conversion

```
$ sqlitebiter url https://docs.google.com/spreadsheets/d/e/XXXXX-XXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXX/pubhtml
```

# b. Download the book
1. Select menu: `File` -> `Download as` -> `Microsoft Excel (.xlsx)`
2. Convert from the downloaded Excel file to a SQLite file by using `sqlitebiter file` subcommand

```
$ sqlitebiter file book.xlsx
```

**Comment by rcf18** [comment]
yap, after we opened a github issue, we did the option b =)
good to learn from you that there is also option a.
thanks for sharing!

**Comment by thombashi** [comment]
I'll close the issue, then.
Feel free to reopen if you still have any other issues.
