### ISSUE TITLE
Invalid data json format

### ISSUE THREAD

**Issue by BILLyTheLiTTle** [thombashi/sqlitebiter#47]
I tried to convert a json which I created here (https://jsoneditoronline.org/) and the application throws the following error:
invalid json data format: path=.\data.json, message='utf-8' codec can't decode byte 0xc5 in position 110: invalid continuation byte.
I am on win10, I am using sqlitebiter 0.12.0 and I attach the json file which contains Greek letters also.
[data.zip](https://github.com/thombashi/sqlitebiter/files/1688545/data.zip)

I also tried from a url (https://api.myjson.com/bins/j055h) , application returns with no error but it creates an SQLite file with 0KB size!

**Comment by thombashi** [comment]
@BILLyTheLiTTle 

Thank you for your report.

Looks like, there are two problems: encoding and JSON-format.
Unfortunately, the latter problem could not be resolved.

# Encoding problem
The encoding error can be avoidable by passing appropriate encoding to `--encoding` option:

```
$ sqlitebiter file --encoding "ISO 8859-7" data.json
```

# JSON format problem
JSON data format in the `data.zip` does not support for sqlitebiter.
Details are described in http://sqlitebiter.readthedocs.io/en/latest/pages/usage/file/index.html

> Available JSON Schema is limited. Acceptable format described in here
