### ISSUE TITLE
build homebrew recipe for sqlitebiter on macos

### ISSUE THREAD

**Issue by wingsuitist** [thombashi/sqlitebiter#48]
https://brew.sh/

**Comment by thombashi** [comment]
Thank you for your suggestion.
I had added the Homebrew installation for macOS: https://github.com/thombashi/sqlitebiter/blob/master/docs/pages/installation.rst#installation-for-macos-via-homebrew

**Comment by wingsuitist** [comment]
wow, thank you so much!

**Comment by thombashi** [comment]
I'll close the issue.
Thanks.
