### ISSUE TITLE
Option -f for format only available in url command

### ISSUE THREAD

**Issue by wingsuitist** [thombashi/sqlitebiter#49]
https://github.com/thombashi/sqlitebiter/blob/3e2ae469ca2b344c942bbd11fb0883ea969c1013/docs/pages/usage/url/help.txt#L11

**Comment by thombashi** [comment]
Thank you for your issue.
I had added the `--format` option to the file sub command at `sqlitebiter 0.14.0`

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you have any problems about the feature.
