### ISSUE TITLE
Feature: support duplicated column name from excel files

### ISSUE THREAD

**Issue by thomasleveil** [thombashi/sqlitebiter#55]
Given that row 1 in a excel file defines columns' name, it is valid to have multiple columns with the same name in excel.

Could `sqlitebiter file xxxxx.xls` with such a file could handle the case instead of raising the `sqlite3.OperationalError: duplicate column name: COUNTRY` error? Maybe by using a suffix `_2` for the second column with a given name?

**Comment by thombashi** [comment]
@thomasleveil 
Thank you for your feedback.

I had released ``sqlitebiter 0.18.0``, this version automatically renames duplicate column names (adding suffix as you mentioned).
e.g. duplicated columns like ``A, A, A, A_1, A_1`` will rename to ``A, A_2, A_3, A_1, A_1_1``.

Please try this version.

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.

**Comment by thomasleveil** [comment]
Thank you for this quick update. I had the occasion to use sqlitebiter with such a excel file this morning and everything went fine. Great work!

**Comment by thombashi** [comment]
Thank you for your confirmation!
