### ISSUE TITLE
Unable to use named pipe with sqlitebiter file

### ISSUE THREAD

**Issue by fproulx-eoscanada** [thombashi/sqlitebiter#56]
I'm trying to create SQLite from a large (multi-gigabytes) gziped JSONL file.

I tried to create a named pipe (mkfifo) , gzcat my file to the named pipe and use it as input to sqliter file, but it gives me "not a file" error.

Am I doing something wrong, or you do not support named pipes, is there a good reason?

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
