### ISSUE TITLE
can you make it more json instagram friendly ?!

### ISSUE THREAD

**Issue by minanagehsalalma** [thombashi/sqlitebiter#61]
https://superuser.com/questions/1412477/how-can-i-view-my-instagram-backup-data-in-a-friendly-way

**Comment by thombashi** [comment]
@minanagehsalalma 
I am not sure what you are asking for.
Are you trying to convert Instagram backup files to a SQLite database?

**Comment by minanagehsalalma** [comment]
@thombashi  "Are you trying to convert Instagram backup files to a SQLite database?"

yes in an easy readable format

**Comment by thombashi** [comment]
I am still not sure what you trying to do.
Did you consider SQLite database is an easily readable format? and the link seems does not clearly describe what is readable in this case.
If you meant the output table of sqlitebiter is not your expected format, you could process JSON data with [jq]( https://stedolan.github.io/jq/ ) command

**Comment by minanagehsalalma** [comment]
@thombashi  can you test it for me ?

**Comment by thombashi** [comment]
Please do it yourself.
I could not understand what you trying to do.

Processing data with jq is out of scope with this project.
jq has tutorial and manual, and described the top page as follows:

>Ask questions on stackoverflow using the jq tag, or on the #jq channel on Freenode.
