### ISSUE TITLE
feature request: add option to disable type inference when parsing the input

### ISSUE THREAD

**Issue by aborruso** [thombashi/sqlitebiter#64]
Hi,
reading [this reply](https://github.com/thombashi/sqlitebiter/issues/62#issuecomment-475289745) I have discovered that sqlitebiter do field type inference, when collect data starting from a webpage.

Now there is `--convert-config` option that enables to set field type for every field.

I think that for some complex source could be long and boring to set field type for a lot of fields.
A solution could be to add a `-I` parameter  to disable type inference when parsing the input, and have all field type set as text.

Thank you

**Comment by thombashi** [comment]
Hi,

Thank you for your suggestion.

That sounds reasonable.
I will consider for the future release.

**Comment by thombashi** [comment]
I had added `--no-type-inference` option at `sqlitebiter 0.27.0` that disable type inference.

Example:

## Input data
```
$ cat issue64.csv
A,B
abc,1
xyz,2
```

## w/o `--no-type-inference`
```
$ sqlitebiter file issue64.csv
```

### Output
|Field| Type  |Null|Key|Default|Index|Extra|
|-----|-------|----|---|-------|:---:|-----|
|A    |TEXT   |YES |   |NULL   |     |     |
|B    |INTEGER|YES |   |NULL   |     |     |


## w/ `--no-type-inference`
```
$ sqlitebiter --no-type-inference file issue64.csv
```

### Output
|Field|Type|Null|Key|Default|Index|Extra|
|-----|----|----|---|-------|:---:|-----|
|A    |TEXT|YES |   |NULL   |     |     |
|B    |TEXT|YES |   |NULL   |     |     |

**Comment by aborruso** [comment]
WOW!!!

I'm really happy and proud.

Thank you
