### ISSUE TITLE
Trying to connect to Google Sheet

### ISSUE THREAD

**Issue by Dannyad84** [thombashi/sqlitebiter#66]
my line: sqlitebiter -o db.sqlite3 gs client_secret.json FA

Error:  'Expected', client.SERVICE_ACCOUNT)
ValueError: ('Unexpected credentials type', None, 'Expected', 'service_account')

Thanks!

**Comment by thombashi** [comment]
Hi,

Looks like your credential file is not valid.
Please check Google Sheet credential settings.

for your reference: https://gspread.readthedocs.io/en/latest/oauth2.html

**Comment by Dannyad84** [comment]
I figured that but I got it from the website. Is it looking for a certain field? I'm also using this on a Django site. Any tips?

**Comment by thombashi** [comment]
> I figured that but I got it from the website. 

Did you mean created a credential file with Google API console?

> Is it looking for a certain field? 

Yes. A valid credential file will include: 

```json
"type": "service_account",
```

the error indicates that the above field not included in your credential file.

The following comment may help:
https://github.com/burnash/gspread/issues/393#issuecomment-355294795

**Comment by thombashi** [comment]
I'll close the issue.
Feel free to reopen if you still have any problems about the issue.
