### ISSUE TITLE
how build sqlitebiter on armhf(32bit)

### ISSUE THREAD

**Issue by mozeat-sun** [thombashi/sqlitebiter#67]
hi，
    sqlitebiter is a powerful tool, could build the source on embedded system,such as armhf-32bit.

**Comment by thombashi** [comment]
Hi,

I never tried it before, but you could build an executable binary file for arm  as follows:

1. Install `pyinstaller`
    - `pip install pyinstaller>=3.4`
    - You might need to install extra apt packages to build `pyinstaller`
2. Clone `sqlitebiter` repository (or download the source code)
3. Execute `build_deb_package.sh`
    - You might need to change `Architecture` https://github.com/thombashi/sqlitebiter/blob/89bd4049024036d92bc04462836f0100d018497a/build_deb_package.sh#L36

**Comment by mozeat-sun** [comment]
thanks  , i had installed it successfully by your indication.

**Comment by thombashi** [comment]
Thank you for confirmation. Closing.
