### ISSUE TITLE
EXCEL with images

### ISSUE THREAD

**Issue by pkoppstein** [thombashi/sqlitebiter#69]
My EXCEL spreadsheet has some images (.jpg) in some cells. I was hoping to be able to use sqlitebiter to convert the spreadsheet to an SQLITE database, since SQLITE3 handles images in cells properly (using BLOBs).  However:

```
sqlitebiter -o  Test.db file "Test.xlsx"
[WARNING] sqlitebiter file: convertible table not found in Test_shareability.xlsx
[INFO] sqlitebiter file: converted results: source=0
```

**Comment by thombashi** [comment]
Unfortunately, sqlitebiter can not convert images in cells due to no measure to read image data currently.
