### ISSUE TITLE
What are the appropriate Google Sheets/Drive/API permissions needed?

### ISSUE THREAD

**Issue by tecnobabble** [thombashi/sqlitebiter#72]
Regardless of the permissions I set, sqlitebiter complains that it can't find any google sheet that I reference.  I've verified the credentials, and even see the google drive list API commands running successfully in the Google API dashboards.  I've tried sharing out the sheets, creating new sheets, etc, but it always complains `OpenError: spreadsheet 'xxxxxx' not found`.  Downloading a CSV from GS and importing it that way works as expected.

Latest version of sqlitebiter (0.29.2), all dependencies installed, etc.

**Comment by thombashi** [comment]
@tecnobabble 
Thank you for your report.

> I've verified the credentials

Let me confirm, did you using service account JSON file described below?
https://gspread.readthedocs.io/en/latest/oauth2.html#oauth-credentials


And, please provide me the following information:

- full command line and the error log
- package version of gspread/oauth2client/pyOpenSSL

**Comment by tecnobabble** [comment]
That was it; needed to explicitly share the doc as it's apparently not included in "share within the organization".  Is this oauth-credentials url in the docs for sqlitebiter and I missed it?

**Comment by thombashi** [comment]
@tecnobabble 
Thank you for your response.

How about the results of the following example.
Does it succeed without errors?

https://gspread.readthedocs.io/en/latest/oauth2.html at 6.

```py
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']

credentials = ServiceAccountCredentials.from_json_keyfile_name('gspread-april-2cd … ba4.json', scope)

gc = gspread.authorize(credentials)

wks = gc.open("Where is the money Lebowski?").get_worksheet(0) # this line need to change appropriate title
```

**Comment by tecnobabble** [comment]
Yes, the command works with the above code format.  My specific issue was with step 4 (https://gspread.readthedocs.io/en/latest/oauth2.html#oauth-credentials):
`Go to your spreadsheet and share it with a client_email from the step above.`
I thought this was done already because it was a spreadsheet that the organization itself owned, but since the service account isn't considered under the organizational domain, it must be explicitly shared.
