### ISSUE TITLE
Feature request: input from stdout

### ISSUE THREAD

**Issue by Izzur** [thombashi/sqlitebiter#75]
It will help with chaining command and using pipe, eg. doing pre-processing of json files with [jq](https://stedolan.github.io/jq/) qnd pipe its output as input for sqlitebiter

**Comment by thombashi** [comment]
@Izzur 
Thank you for your feedback.

I had added `stdin` subcommand at `sqlitebiter 0.32.0`.
You can convert data from stdin like follows:

```
$ echo '[{"hoge": 4, "foo": "abc"}, {"hoge": 12, "foo": "xyz"}]' | sqlitebiter stdin json
[INFO] convert 'stdin' to 'json1' table
[INFO] converted results: source=1, success=1, created-table=1
[INFO] database path: out.sqlite
```
