### ISSUE TITLE
Getting "codec can't decode byte ..." 

### ISSUE THREAD

**Issue by johann-petrak** [thombashi/sqlitebiter#78]
I am converting a tsv file which is in UTF-8.

I am using the "file" subcommand to read from the tsv file. 

I get the error message:
```
[ERROR] DataError: invalid tsv data: path=ads_multi_all_dedupe_gen_dedupe.tsv, message='charmap' codec can't decode byte 0x8f in position 3956: character maps to <undefined>
```

This TSV file can be read into pandas or by myself without any problem at all when the file is read using open(filename, "rt", encoding="utf-8").
Since UTF-8 is mostly the standard for any text file these days, I would have assumed that it would work for a tsv file (which is intrinsically a text file).

Oddly, there seems to be no command line option to specify the encoding of the input file. 

Am I missing something fundamental here?

**Comment by thombashi** [comment]
@johann-petrak 
Thank you for your report.

`sqlitebiter file` subcommand has `--encoding` option that you can specify input files encoding.
Without the option, the command trying to detect the encoding from a file. Perhaps this detection did not work properly for some reason.

If you could provide me the probramatic file I might improve auto encoding detection.
