### ISSUE TITLE
Retain leading zeros when converting text or --no-type-inference

### ISSUE THREAD

**Issue by fburleigh** [thombashi/sqlitebiter#83]
# Describe the bug
Value tokens like 0003530043 and 00126 are converted to text without their leading zeros.

# Expected behavior
Using CLI option --no-type-inference or --type-hint-header with a column that hints text, then the value 0003530043 should be converted as 0003530043 rather than 3530043.

# To Reproduce

1. Given this CSV called zero.csv:
```
column1, column2-text
123, 0123
0123, 123
123, 0123
```
2. And the CLI: `sqlitebiter --type-hint-header -o zero.sqlite file zero.csv`
3. Then after `sqlite3 zero.sqlite`: 
```
.header on;
select * from zero;
```
4. I expect you will see:
```
column1|column2-text
123|123
123|123
123|123
```
5. Verify the table's structure:
```
CREATE TABLE IF NOT EXISTS 'zero'([column1] INTEGER, [column2-text] TEXT);
```

# Environments
Please complete the following information:

- uname: Darwin the-admiralty 18.7.0 x86_64
- CPython version: 3.7.5
- sqlitebiter version: not installed
- SimpleSQLite version: not installed
- pytablereader version: not installed

- **Installation Method:** `brew`

# Additional context
Add any other context (logs, error output, etc.) about the problem here.
(If it’s long, please paste to https://ghostbin.co/ and insert the link here.)

**Comment by thombashi** [comment]
@fburleigh 
Thank you for your report.

I had fixed the problem at `sqlitebiter 0.35.0`.

```
$ sqlitebiter --type-hint-header file issue83.csv
[INFO] convert 'issue83.csv' to 'issue83' table
[INFO] converted results: source=1, success=1, created-table=0
[INFO] database path: out.sqlite
```

```
sqlite> .schema issue83
CREATE TABLE IF NOT EXISTS 'issue83' ([column1] INTEGER, [column2-text] TEXT);
sqlite> select * from issue83;
123|0123
123|123
123|0123
```

Please try to upgrade.
