### ISSUE TITLE
incompatibility between pip V22 json output and sqlitebiter

### ISSUE THREAD

**Issue by piscvau** [thombashi/sqlitebiter#88]
# Describe the bug
pip V22 has a new inspect command which produces a json output. https://github.com/pypa/pip
using sqlitebiter to create a sqlite database with the output raises an exception

# Expected behavior
convert json output to sqlite atabase

# To Reproduce

1. activate a virtual environment
2.  python3 -m pip install pip --upgrade with several packages
3. pip install a few pacakges
4. pip inspect -local >json_output.json
5. sqlitebiter file json_output.json table

# Environments
Please complete the following information:

```
- uname: Linux
- Python version: CPython 3.8.10
- sqlitebiter version: 0.36.1
- platform version: Ubuntu 20.04
- SimpleSQLite version: 1.3.0
- pytablereader version: 0.31.3
```

- **Installation Method:** `pip` / `deb package ` / `apt(PPA)` / `brew` (choose one of these)

# Additional context
trace is in https://bpa.st/J5SQ
json file renamed in .txt 
[json_local_requirements.txt](https://github.com/thombashi/sqlitebiter/files/9280729/json_local_requirements.txt)

**Comment by thombashi** [comment]
@piscvau 
You might convert the JSON value to convertible format with `jq` command.
e.g. https://github.com/thombashi/sqlitebiter/issues/58#issuecomment-532936700
