### ISSUE TITLE
Convert &nbsp; to spaces

### ISSUE THREAD

**Issue by nolageek** [thombashi/sqlitebiter#92]
# Describe the bug
When using sqlitebiter.exe to pull URL into a sqlite3 database, &nbsp; non-breaking spaces are not converted to ASCII spaces. Not sure if this is a bug or expected behavior but it is causing encoding issues when making queries.

# Expected behavior
Expecting spaces to be displayed, instead I'm getting encoding errors.

# To Reproduce

On windows:
1. sqlitebiter.exe url 'https://horrorcons.com/calendar/'
2. Search in table Future_Horror_Convention_Calendar_HorrorCons_com_ConListTable for the following: "Final Girl Festival 2023"
3.  The date column contains "June 30 - July 2, 2023" which is actually "`June&nbsp;30 - July&nbsp;2, 2023`" 

# Environments
Please complete the following information:

```
C:\utils>sqlitebiter.exe version
- uname: Windows
- Python version: CPython 3.8.10
- sqlitebiter version: 0.36.1
- platform version: 10 10.0.19045 SP0
- SimpleSQLite version: not installed
- pytablereader version: not installed
```

- **Installation Method:** `pip` / `deb package ` / `apt(PPA)` / `brew` (choose one of these)
Downloaded windows release from github.

# Additional context
Add any other context (logs, error output, etc.) about the problem here.
(If it’s long, please paste to https://ghostbin.co/ and insert the link here.)

**Comment by nolageek** [comment]
Any thoughts on this?

**Comment by thombashi** [comment]
@nolageek 
Thank you for your report.
It looks like the source contents include `&nbsp` characters, and `sqlitebiter` keep the values as it is.
I might be adding an option to unescape the source before conversion.

For a while, you can workaround the issue by the following:
1. fetch the contents and write them to a local file
2. unescape the file
3. execute `sqlitebiter file ` command
